name: SpotifyCatalogAPI tests

on:
  pull_request:
    branches:
      - main  # This will trigger on PRs to the 'main' branch

jobs:
  TriggerDeployment:
    runs-on: ubuntu-latest
    needs: Build  # This means this job will run after the 'Build' job completes successfully.
    env:
      SPOTIFY_TESTING_REPO_NAME: SpotifyTesting  # Change this to the correct name of the 'SpotifyTesting' repo.
      UI_TESTING_WORKFLOW_ID: ui_testing  # Replace with the correct workflow ID from SpotifyTesting.
    steps:
      - name: Trigger the Selenium testing workflow
        run: |
          curl -X POST \
           -H "Authorization: Bearer ${{ secrets.GITHUB_ACCESS_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           -d "{\"ref\": \"main\", \"inputs\": {\"browser\": \"chrome\"}}" \
           https://api.github.com/repos/$SPOTIFY_TESTING_REPO_NAME/actions/workflows/$UI_TESTING_WORKFLOW_ID/dispatches
